<?php
  
  //Page Title
  $this->headTitle('ZF2');
  $this->headTitle($this->translate('App Skeleton'))->setSeparator(' - ')->setAutoEscape(false);
  
  //Meta Tags
  $this->headMeta()->appendName('description','App Skeleton for ZF2 Applications')
                  ->appendName('author', 'Daniel Wolkenhauer')
                  ->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
                  ->appendName('apple-mobile-web-app-capable', 'yes')
                  ->appendName('apple-mobile-web-app-status-bar-style','black');

  $this->headLink(array(
    'rel' => 'icon',
    'extras' => array(
      'type' => 'image/svg+xml',
      'sizes' => 'any'
    ),
    'href' => $this->basePath('img/favicon.svg'),
  ));

  // $this->headLink()->prependStylesheet($this->basePath('css/style.css'))
  //                 ->prependStylesheet($this->basePath('css/bootstrap.css'));
  $this->headLink()->prependStylesheet($this->basePath('css/base.css'))

?>

<?php echo $this->doctype(); ?>
<html lang="de">
<head>
  <meta charset="utf-8">
  <?php
    echo $this->headTitle();
    echo $this->headMeta();
    echo $this->headLink();
  ?>
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#"><img src="../../../../img/zf-logo-mark.png" alt="" height="40px"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle Nav">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Startseite
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">UI</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Documentation</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Tests</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <?php echo $this->content; ?>

  <footer class="py-5 bg-dark">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
          <ul class="list-inline mb-2">
            <li class="list-inline-item">
              <a href="#">About</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Contact</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Terms of Use</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Privacy Policy</a>
            </li>
          </ul>
          <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2019. All Rights Reserved.</p>
        </div>
        <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
          <ul class="list-inline mb-0">
            <li class="list-inline-item mr-3">
              <a href="#">
                <i class="fab fa-facebook fa-2x fa-fw"></i>
              </a>
            </li>
            <li class="list-inline-item mr-3">
              <a href="#">
                <i class="fab fa-twitter-square fa-2x fa-fw"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-instagram fa-2x fa-fw"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

  <?php
    $this->inlineScript()->prependFile($this->basePath('js/bootstrap.bundle.js'))
                            ->prependFile($this->basePath('js/jquery-3.4.1.js'));
  ?>
  <?php echo $this->inlineScript() ?>
  <script type="text/javascript" src="http://jira.dw-labs.de/s/c7f3ee97856bca1ade27a05b07875f7a-T/jcp5fx/72004/be09033ea7858348cd8d5cdeb793189a/2.0.21/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?locale=de-DE&collectorId=246f92df"></script>
  
</body>
</html>
