  <header class="bg-green-gradient py-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Welcome to Zend Framework 2</h1>
          <p class="lead mb-5 text-white-50">Herzlichen Glückwunsch, Deine App ist betriebsbereit! Diese Vorlage soll dabei helfen, Zend Framework 2 Anwendungen schnell zum Laufen zu bringen. <br /><br />Aktuell ist Version <strong>2.4.13</strong> des Zend Frameworks installiert.</p>
        </div>
      </div>
    </div>
  </header>

  <section class="features-icons bg-light text-center mb-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-screen-desktop m-auto text-success"></i>
            </div>
            <h3>Stable</h3>
            <p class="lead mb-0">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-layers m-auto text-success"></i>
            </div>
            <h3>Extensible</h3>
            <p class="lead mb-0">At vero eos et accusam et justo ea rebum. Stet clita kasd gubergre amet.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-check m-auto text-success"></i>
            </div>
            <h3>Ready to Use</h3>
            <p class="lead mb-0">Ready to use with your own content, or customize the source files!</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <div class="container mb-5">

    <div class="row">

      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <p><hr></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="#"><button type="button" class="btn btn-sm btn-outline-secondary">View on Github</button></a>
              </div>
              <span class="badge badge-warning">In Progress</span>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus.</p>
            <p><hr></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="#"><button type="button" class="btn btn-sm btn-outline-secondary">View on Github</button></a>
              </div>
              <span class="badge badge-success">Done</span>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente necessitatibus doloribus totam ut praesentium aut.</p>
            <p><hr></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="#"><button type="button" class="btn btn-sm btn-outline-secondary">View on Github</button></a>
              </div>
              <span class="badge badge-warning">In Progress</span>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
            <p><hr></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="#"><button type="button" class="btn btn-sm btn-outline-secondary">View on Github</button></a>
              </div>
              <span class="badge badge-primary">ToDo</span>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <p><hr></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="#"><button type="button" class="btn btn-sm btn-outline-secondary">View on Github</button></a>
              </div>
              <span class="badge badge-primary">ToDo</span>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus.</p>
            <p><hr></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="#"><button type="button" class="btn btn-sm btn-outline-secondary">View on Github</button></a>
              </div>
              <span class="badge badge-primary">ToDo</span>
            </div>
          </div>
        </div>
      </div>
      
    </div>

  </div>
